### ISSUE TITLE
Make a footer 

### ISSUE THREAD

**Issue by MSami625** [CyberCellGu/CyberCell-New#14]
![Screenshot 2023-10-02 183123](https://github.com/CyberCellGu/CyberCell-New/assets/77672838/fa58f861-2133-4474-b252-18236ce1ace7)

# this image is for rough idea use your creativity. in place of cybrary  Use CyberCell

**Comment by sarangyogi** [comment]
I want to work on this issue. Could you please assign me @MSami625
