### ISSUE TITLE
Make About Us Section.

### ISSUE THREAD

**Issue by MSami625** [CyberCellGu/CyberCell-New#16]
We welcome all ideas, Design about us section in your way it should look modern and match theme.

**Comment by RSN601KRI** [comment]
Hey, Can you please assign me this?

**Comment by Virentanti** [comment]
I’m interested, Can you please assign this to me

**Comment by MSami625** [comment]
Viren you can start work on about us section , it  will be on landing page and also use some images in about us ..try to make it cool and match the cybercell overall theme.

**Comment by Virentanti** [comment]
@MSami625 what is the deadline for the issue?

**Comment by MSami625** [comment]
NO deadline for now work with no worries .if you are participating in hacktoberfest the try to do before end of october.

**Comment by Sharnabh** [comment]
Heyy, can you please assign my this section

**Comment by MSami625** [comment]
@Sharnabh  wait sometime then fork the current repo contains some errors.

**Comment by Sharnabh** [comment]
@MSami625 the repo is showing some errors

**Comment by MSami625** [comment]
There were some errors we have fixed them just need to merge them will be done by today.

**Comment by MSami625** [comment]
@Sharnabh  you can pull latest code , errors are fixed now.

**Comment by Virentanti** [comment]
I am working on about us section but instruction is unclear... do i make about us section above footer or make a whole page for about us and i require text and an image for about us section.

**Comment by duplixx** [comment]
@Virentanti hey u have to make about us page and link it to navbar use your creativity and follow the themeof whole website to make it a awsomee about us

**Comment by shineishukla** [comment]
@MSami625 Hey I would like to work on this isuue can you please assign it to me.
