### ISSUE TITLE
Link Login and Register component with Strapi backend.

### ISSUE THREAD

**Issue by MSami625** [CyberCellGu/CyberCell-New#20]
// Quick start guide for strapi
https://docs.strapi.io/dev-docs/quick-start#_1-install-strapi-and-create-a-new-project

**Comment by RSN601KRI** [comment]
Hey, can you assign me this?

**Comment by HariKrishna-28** [comment]
Hello! I would like to contribute to this issue. Could you please tell me more on what to do? @MSami625

**Comment by MSami625** [comment]
We want a login and register page which uses strapi which will make easy to implement all backend features. You can read about strapi through docs mentioned above. if you want i can assign .

**Comment by Tholkappiar** [comment]
What kind of features are needed here ,  in this issue , just login and register ? Could you provide the details about this !

**Comment by AyushmanSinghRajawat** [comment]
Hey, @MSami625 i have read the strapi docs and would like to work on this. Kindly assign me this isssue. If you have any other suggestion or any specific requirement please let me know.

**Comment by AyushmanSinghRajawat** [comment]
Sorry @MSami625 i am currently busy on an another personal project and would not like to put this one on hold any further, so if anyone else would like to contribute please do. I will contribute in to this repo in future. Hope you understand. Cheers🍻
