### ISSUE TITLE
Create Event Page API's

### ISSUE THREAD

**Issue by duplixx** [CyberCellGu/CyberCell-New#27]
API Schema should consist:
{
  "Event": {
    "Heading": "Your Event Heading",
    "Details": "Event details go here.",
    "Time": "Event time goes here.",
    "Venue": "Event venue goes here.",
    "Fees": "Event fees go here."
  }
}

**Comment by Sharnabh** [comment]
do I have to create a strapi collection type ??

**Comment by Sharnabh** [comment]
I am intrested, can you assign it to me ??

**Comment by duplixx** [comment]
yes this is collection type and you have to create api's

**Comment by Sharnabh** [comment]
@duplixx do you want to add the event info through the web page or directly from strapi?

**Comment by duplixx** [comment]
from strapi itself
