### ISSUE TITLE
Improvement : Improving UI in the Landing Page

### ISSUE THREAD

**Issue by Tholkappiar** [CyberCellGu/CyberCell-New#31]
**Issue :** _Improving UI in the Landing Page_

**To Reproduce :** 

_visit :_  https://cybercell.netlify.app/

**Images :** 

![cybercell](https://github.com/CyberCellGu/CyberCell/assets/114584730/61ffc266-6cf9-45fd-9865-3a07b3e01fbf)

**Solution :** 

- Improving landing page more Attractive.
- Remove Dummy Texts ( Lorem )

**PS : Assign this issue to Me.**

**Comment by MSami625** [comment]
ok i will assign issue to you but there are some errors in repo , errors are fixed but need to be merged so wait some time then fork latest code .

**Comment by Tholkappiar** [comment]
Okay , when it is done let me know !

**Comment by MSami625** [comment]
@Tholkappiar  Are you working on this issue?

**Comment by Tholkappiar** [comment]
Yeah bro will complete it today ASAP ! Sorry for the delay .

**Comment by Tholkappiar** [comment]
**Fixed the FAQ section UI.** #39 . 
Thank you for your time and consideration. Looking forward to hear from you soon.

_Best regards,_
**Tholkappiar**
