### ISSUE TITLE
create signup form which matched the theme of login form

### ISSUE THREAD

**Issue by duplixx** [CyberCellGu/CyberCell-New#33]
![image](https://github.com/CyberCellGu/CyberCell/assets/90516956/f0422885-9bb6-42eb-bbda-86b54dd1a2dc)

**Comment by insane-22** [comment]
Hey @duplixx , 
I would like to contribute to your project under hacktoberfest 2023, kindly assign this issue to me.
Thank you for your consideration

**Comment by insane-22** [comment]
@duplixx , also there is already a signup form created in the code, would you like me to change it or keep it the same?

**Comment by insane-22** [comment]
Thankyou @duplixx  for assigning this issue to me, I hope I would be able to contribute to the project in the best way possible. Kindly tell if I should link the already created register page, or create one similar to login page, so that I can start working on the project.

**Comment by duplixx** [comment]
you can link the already existing one and make changes to it
