### ISSUE TITLE
[Enhancement] Improve User Interface for Hero Data 

### ISSUE THREAD

**Issue by Abhishek9503** [CyberCellGu/CyberCell-New#37]
Hero data section does not match with the ui of the website so there should be a updation in the ui of the hero data section

![Screenshot (1442)](https://github.com/CyberCellGu/CyberCell/assets/103676667/6b394962-32c6-4385-8c15-256c380d9316)

**Comment by duplixx** [comment]
@Abhishek9503 code well!!
