### ISSUE TITLE
[Fix]:Hacktivists page data not aligned correctly

### ISSUE THREAD

**Issue by Abhishek9503** [CyberCellGu/CyberCell-New#40]
while navigating to Hacktivists page from navbar links the new page of Hacktivists is not properly aligned and the image is overlapping on the next section

![Fix](https://github.com/CyberCellGu/CyberCell/assets/103676667/f0a4a699-639a-4cc5-ac78-0225b1bebc2f)

**Comment by duplixx** [comment]
you can work on that :) and make it awesoome
